### ISSUE TITLE
Create Index of Library Database Content

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#34]
### User story
As a developer I would like to send a keyword search to a service and get back library databases via API. 

### Tasks

- [x] Create new database table that can stored library database content for search. 
- [x] Load the data from the Library Web Databases. See the Web Databases Task: https://github.com/pulibrary/lib_jobs/tree/main/docs/web_database_list for how the database data from libguides is extracted and produced for fruther use. 
- [x] Index keyword fields (Database Name, Description, alternative titles, and subjects). 

### Implementation notes
URL for current database data is URL is  https://lib-jobs.princeton.edu/library-databases.csv.

Take a look at https://github.com/pulibrary/allsearch_rails_api/pull/80/files for possible inspiration
